services:
  moba-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: moba_service_dev
    command: pnpm run start:dev
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    develop:
      watch:
        - path: ./src
          target: /app/src
          action: sync
          ignore:
            - node_modules/
            - dist/
            - .git/
            - .docker/
            - .env
        - path: ./package.json
          target: /app/package.json
          action: sync+restart
        - path: ./tsconfig.json
          target: /app/tsconfig.json
          action: sync+restart
        - path: ./.env
          target: /app/.env
          action: sync+restart

volumes:
  node_modules: 