export enum StatType {
  HEALTH = 'HEALTH',
  MANA = 'MANA',
  STRENGTH = 'STRENGTH',
  DEXTERITY = 'DEXTERITY',
  INTELLIGENCE = 'INTELLIGENCE',
  ARMOR = 'ARMOR',
  MAGIC_RESISTANCE = 'MAGIC_RESISTANCE',
  DAMAGE = 'DAMAGE',
  MAGIC_DAMAGE = 'MAGIC_DAMAGE',
  ACCURACY = 'ACCURACY'
} 