version: '3.8'

services:
  moba-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moba_app
    ports:
      - "${MOBA_APP_PORT:-3001}:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:${MOBA_SERVICE_PORT:-3000}
    logging:
      driver: "json-file"
      options:
        tag: "{{.Name}}"
    networks:
      - moba-app-network

networks:
  moba-app-network:
    driver: bridge 